
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - internal
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - internal
    ports:
      - "6379:6379"       # <- пробросим порт Redis наружу

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    networks:
      - internal

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    env_file: .env
    depends_on:
      - db
      - redis
      - rabbitmq
    networks:
      - internal
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file: .env
    depends_on:
      - db
      - redis
      - rabbitmq
    networks:
      - internal
    restart: unless-stopped

networks:
  internal:
    driver: bridge
