services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - internal
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    networks:
      - internal
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}

  queue-server:
    build:
      context: ../..
      dockerfile: queue_server/Dockerfile
    container_name: queue-server
    depends_on:
      - redis
      - rabbitmq
    restart: unless-stopped
    networks:
      - internal
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_TASK_QUEUE: task_queue
      RABBITMQ_RESULT_QUEUE: result_queue
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

networks:
  internal:
    driver: bridge
