
services:
  redis:
    image: redis:7-alpine
    container_name: queue-redis
    restart: unless-stopped
    networks:
      - internal
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: queue-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - "5672:5672"    # для AMQP
      - "15672:15672"  # для Web UI (http://localhost:15672)
    networks:
      - internal

  queue-server:
    build:
      context: ../..
      dockerfile: queue_server/Dockerfile
    container_name: queue-server
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - redis
    env_file:
      - .env
    networks:
      - internal
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

networks:
  internal:
    driver: bridge
