version: '3.9'

services:
  worker:
    build:
      context: ../..          # корень проекта с Dockerfile.worker
      dockerfile: Dockerfile.worker
    env_file:
      - ../../.env            # ваши переменные окружения с RABBITMQ_HOST, POSTGRES_HOST и т.п.
    restart: unless-stopped
