version: '3.9'
services:
  worker:
    build:
      context: ../..                       
      dockerfile: Dockerfile.worker         
    env_file:
      - ../../.env                          
    depends_on:
      - db
      - redis
      - rabbitmq
    networks:
      - internal
    restart: unless-stopped

networks:
  internal:
    external: true
