services:
  worker:
    container_name: riverai-worker-1
    build:
      context: ../..
      dockerfile: Dockerfile.worker
    restart: unless-stopped
    env_file:
      - ../../.env         # обычный .env (общий)
      - ../../.env.override  # временный секрет из GitHub Actions
    networks:
      - riverai-network
    environment:
      - TELEGRAM_ID_SALT   # обязательно пробрасываем внутрь контейнера

networks:
  riverai-network:
    external: true
