
services:
  worker:
    build:
      context: ../..            # корень репо с Dockerfile.worker
      dockerfile: Dockerfile.worker
    env_file:
      - ../../.env              # подтянет POSTGRES_HOST, RABBITMQ_HOST, REDIS_HOST и др.
    restart: unless-stopped
    networks:
      - internal

networks:
  internal:
    driver: bridge
