services:
  worker:
    container_name: riverai-worker-1
    build:
      context: ../..
      dockerfile: Dockerfile.worker
    restart: unless-stopped
    env_file:
      - ../../.env
    networks:
      - riverai-network

networks:
  riverai-network:
    external: true
