version: "3.9"

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - internal
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    networks:
      - internal

  queue-server:
    build:
      context: ../..
      dockerfile: queue_server/Dockerfile
    container_name: queue-server
    restart: unless-stopped
    depends_on:
      - redis
      - rabbitmq
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_TASK_QUEUE: task_queue
      RABBITMQ_RESULT_QUEUE: result_queue
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - internal


networks:
  internal:
    driver: bridge
