version: '3.9'

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - internal

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - "15672:15672"    # UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - internal

networks:
  internal:
    driver: bridge
