version: '3.9'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"       # <-- публикуем порт
    restart: unless-stopped
    networks:
      - internal

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - "15672:15672"   # UI
      - "5672:5672"     # AMQP для бота
    networks:
      - internal
    restart: unless-stopped

networks:
  internal:
    driver: bridge
