version: '3.9'
services:
  db:
    image: postgres:14
    env_file:
      - ../../.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal
    restart: unless-stopped

networks:
  internal:
    driver: bridge
