services:
  bot:
    build:
      context: ../..       # корень репо, где лежат Dockerfile.bot и всё приложение
      dockerfile: Dockerfile.bot
    env_file:
      - ../../.env         # подтянет DB_HOST, REDIS_HOST, RABBITMQ_HOST и т.д.
    networks:
      - internal
    restart: unless-stopped

networks:
  internal:
    external: true         # эта сеть уже создаётся вашим compose для очереди/БД
