version: '3.9'

services:
  bot:
    build:
      context: ../..       # корень репо с Dockerfile.bot
      dockerfile: Dockerfile.bot
    env_file:
      - ../../.env         # подтянет DB_HOST, REDIS_HOST, RABBITMQ_HOST и т.д.
    restart: unless-stopped
    networks:
      - internal

networks:
  internal:
    driver: bridge
