name: авто-деплой на сервера
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: очередь
            host: 185.200.176.96      # очередь
            secret_key: SSH_KEY_QUEUE
          - name: основной
            host: 185.200.176.99      # основной
            secret_key: SSH_KEY_BASED
          - name: резервный
            host: 185.200.176.97      # резервный
            secret_key: SSH_KEY_RESERVE
          - name: воркер1-2
            host: 185.200.176.95      # воркеры 1 и 2
            secret_key: SSH_KEY_WORKER
          - name: воркер3-4
            host: 185.200.176.98      # воркеры 3 и 4
            secret_key: SSH_KEY_WORKER

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to ${{ matrix.name }}
        uses: appleboy/ssh-action@v0.1.8
        with:
          host:     ${{ matrix.host }}
          username: root
          key:      ${{ secrets[ matrix.secret_key ] }}
          insecure: true                     # <-- вот это вместо use_insecure_known_hosts
          script: |
            cd /opt/ii-tutor-bot
            git pull origin main
            docker-compose up -d --build
