name: авто-деплой на сервера
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: очередь
            host: 185.200.176.96
            secret_key: SSH_KEY_QUEUE
          - name: основной
            host: 185.200.176.99
            secret_key: SSH_KEY_BASED
          - name: резервный
            host: 185.200.176.97
            secret_key: SSH_KEY_RESERVE
          - name: воркер1-2
            host: 185.200.176.95
            secret_key: SSH_KEY_WORKER
          - name: воркер3-4
            host: 185.200.176.98
            secret_key: SSH_KEY_WORKER

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Вариант A: автоматически добавляем known_hosts
      - name: Add ${{ matrix.name }} to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ matrix.host }} >> ~/.ssh/known_hosts

      - name: Deploy to ${{ matrix.name }}
        uses: appleboy/ssh-action@v1.2.2
        with:
          host:     ${{ matrix.host }}
          username: root
          key:      ${{ secrets[ matrix.secret_key ] }}
          # вариант B вместо ssh-keyscan:
          # args: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
          script: |
            cd /opt/ii-tutor-bot
            git pull origin main
            docker-compose up -d --build
